---
title: "Project Component 1"
author: "Himanshu, MDS202327"
date: "`r Sys.Date()`"
output:
  pdf_document: default
  html_document: default
---
```{r setup, include=FALSE} 
knitr::opts_chunk$set(warning = FALSE, message = FALSE) 
```

## Introduction
TBA

## Data Description
The data contains six air pollution parameters like PM2.5, PM10, NO2, NH3, SO2, Ozone for 12 stations in New Delhi, collected from CPCB website from 08-02-2018 to 02-01-2021 on daily basis.

```{r}
# Importing libraries
library(tidyverse)
library(dplyr)
library(ggplot2)
library(TSstudio)
library(plotly)
```

```{r}
# Reading the data into data frame
df <- read.csv("delhi.csv", header = TRUE)
set.seed(5)
df[sample(nrow(df), 5), ]
```
```{r}
# Variables in the data
names(df)
```
```{r}
# Dimension of the data
dim(df)
```
```{r}
# Variable types
# Note the Date column has type chr which must be converted to date type.
str(df)
```

```{r}
df$Date <- as.Date(df$Date)
df[sample(nrow(df), 5), ]
```
```{r}
str(df)
```
```{r}
unique(df$siteName)
```
```{r}
par(mfrow = c(2,3))
hist(df[df$siteCode==1420,]$PM2.5, probability = TRUE, main = "", xlab = "PM2.5", ylab = "")
hist(df[df$siteCode==1420,]$PM10, probability = TRUE, main = "Ashok Vihar", xlab = "PM10", ylab = "")
hist(df[df$siteCode==1420,]$NO2, probability = TRUE, main = "", xlab = "NO2", ylab = "")
hist(df[df$siteCode==1420,]$NH3, probability = TRUE, main = "", xlab = "NH3", ylab = "")
hist(df[df$siteCode==1420,]$SO2, probability = TRUE, main = "", xlab = "SO2", ylab = "")
hist(df[df$siteCode==1420,]$Ozone, probability = TRUE, main = "", xlab = "Ozone", ylab = "")
```
```{r, fig.width=15, fig.height=12}
par(mar=c(2,2,2,2))
par(mfrow=c(5,2))
for (i in unique(df$siteName)) {
  plot(df[df$siteName==i,]$Date, df[df$siteName==i,]$PM2.5, type = "l",
  main = i, xlab = "", ylab = "")
}
```
\center Figure: The above graph shows the time series plot of PM2.5 parameter for all 10 stations in the data.

## Exploratory Data Analysis

```{r}
```

## Results

```{r}
```

## Conclusion

```{r}
```
